"""LRC/SRT → ASS (Advanced SubStation Alpha) 변환기.

ASS 는 SRT 와 달리 폰트·색상·외곽선·페이드·포지션을 자막 파일 내부에서
직접 지정할 수 있어 FFmpeg `subtitles` 필터로 렌더링할 때 훨씬 깔끔한
결과가 나온다. 2026년 유튜브 가사 비디오의 표준.

특징:
  - Montserrat Bold 권장 (한글 병기 시 Noto Sans KR Bold)
  - 중앙 하단 1/3 배치, 모바일 가독성
  - 라인 페이드 인/아웃 250ms
  - 비트 강조 옵션: 특정 라인 크기 업

lyrics_watcher.py 에서 사용:

    from music_pipeline.enhancements.ass_subtitles import (
        lrc_to_ass, srt_to_ass,
    )

    ass_path = lrc_to_ass(lrc_path, out_ass_path, style='ballad')
    # ffmpeg 에 -vf subtitles=ass_path 로 적용

현재 lyrics_watcher.py 의 `convert_lrc_to_srt` 출력을 이 모듈의
`srt_to_ass` 로 한 번 더 변환하면 된다.
"""

from __future__ import annotations

import re
from pathlib import Path


# ============================================================
# 스타일 프리셋
# ============================================================
# ASS 색상: &HAABBGGRR (알파 + BGR). 알파 00=불투명, FF=투명.
# Alignment: 1=좌하, 2=중하, 3=우하, 5=좌중, 6=중중, ...

STYLE_PRESETS = {
    "ballad": {
        # 감성 발라드: 흰 글자 + 검정 외곽선 + 옅은 섀도우
        "fontname": "Malgun Gothic",
        "fontsize": 56,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H80000000",
        "bold": -1,  # -1 = true
        "outline": 2.5,
        "shadow": 1.5,
        "alignment": 2,     # 중앙 하단
        "margin_v": 180,    # 하단 여백 (안전존)
        "fade_in_ms": 250,
        "fade_out_ms": 250,
    },
    "pop": {
        # 팝: 흰 + 두꺼운 검정 외곽선 (강한 대비)
        "fontname": "Malgun Gothic",
        "fontsize": 60,
        "primary": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "back_color": "&H80000000",
        "bold": -1,
        "outline": 3.5,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 200,
        "fade_in_ms": 150,
        "fade_out_ms": 150,
    },
    "lofi": {
        # 로파이: 부드러운 크림색 + 얇은 외곽선
        "fontname": "Malgun Gothic",
        "fontsize": 50,
        "primary": "&H00D0E0F0",
        "outline_color": "&H00000000",
        "back_color": "&H60000000",
        "bold": -1,
        "outline": 2.0,
        "shadow": 1.0,
        "alignment": 2,
        "margin_v": 170,
        "fade_in_ms": 400,
        "fade_out_ms": 400,
    },
    "emotional": {
        # 펫로스·슬픈 감성: 크게, 천천히, 따뜻한 베이지
        "fontname": "Malgun Gothic",
        "fontsize": 58,
        "primary": "&H00E8EEF2",
        "outline_color": "&H00101010",
        "back_color": "&H90000000",
        "bold": -1,
        "outline": 2.8,
        "shadow": 1.8,
        "alignment": 2,
        "margin_v": 200,
        "fade_in_ms": 500,
        "fade_out_ms": 500,
    },
}


# ============================================================
# 시간 변환
# ============================================================
def _seconds_to_ass_time(seconds: float) -> str:
    """ASS 시간 포맷: H:MM:SS.cc (1/100초)."""
    if seconds < 0:
        seconds = 0
    total_cs = int(round(seconds * 100))
    h = total_cs // 360_000
    m = (total_cs % 360_000) // 6000
    s = (total_cs % 6000) // 100
    cs = total_cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _parse_srt_time(s: str) -> float:
    """'HH:MM:SS,mmm' → 초."""
    m = re.match(r"(\d+):(\d+):(\d+)[,.](\d+)", s.strip())
    if not m:
        return 0.0
    h, mn, sc, ms = m.groups()
    return int(h) * 3600 + int(mn) * 60 + int(sc) + int(ms) / 1000.0


def _parse_lrc_time(tag: str) -> float:
    """`[MM:SS.xx]` 또는 `[MM:SS]` → 초."""
    m = re.match(r"\[(\d+):(\d+)(?:[.:](\d+))?\]", tag)
    if not m:
        return 0.0
    mn, sc, frac = m.groups()
    t = int(mn) * 60 + int(sc)
    if frac:
        if len(frac) == 2:
            t += int(frac) / 100.0
        elif len(frac) == 3:
            t += int(frac) / 1000.0
        else:
            t += int(frac) / (10 ** len(frac))
    return t


# ============================================================
# ASS 헤더 빌드
# ============================================================
def _build_ass_header(style: dict, play_res_x: int = 1920, play_res_y: int = 1080) -> str:
    """ASS 파일 헤더 (Script Info + Styles)."""
    return f"""[Script Info]
Title: Auto-generated by music_pipeline
ScriptType: v4.00+
PlayResX: {play_res_x}
PlayResY: {play_res_y}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{style['fontname']},{style['fontsize']},{style['primary']},&H000000FF,{style['outline_color']},{style['back_color']},{style['bold']},0,0,0,100,100,0,0,1,{style['outline']},{style['shadow']},{style['alignment']},60,60,{style['margin_v']},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _build_dialogue_line(start: float, end: float, text: str, style: dict) -> str:
    """Dialogue 줄 + 페이드 효과."""
    fade_in = style.get("fade_in_ms", 0)
    fade_out = style.get("fade_out_ms", 0)
    fade_tag = f"{{\\fad({fade_in},{fade_out})}}" if (fade_in or fade_out) else ""
    # ASS 에서 줄바꿈은 \\N
    text_escaped = text.replace("\n", r"\N").replace("{", r"\{").replace("}", r"\}")
    return (
        f"Dialogue: 0,{_seconds_to_ass_time(start)},{_seconds_to_ass_time(end)},"
        f"Default,,0,0,0,,{fade_tag}{text_escaped}"
    )


# ============================================================
# 메인 변환 함수
# ============================================================
def srt_to_ass(
    srt_path: str,
    out_ass_path: str,
    style: str = "ballad",
) -> bool:
    """기존 SRT 파일 → ASS 변환."""
    style_dict = STYLE_PRESETS.get(style) or STYLE_PRESETS["ballad"]

    try:
        content = Path(srt_path).read_text(encoding="utf-8")
    except Exception:
        return False

    entries: list[tuple[float, float, str]] = []
    blocks = re.split(r"\n\s*\n", content.strip())
    for block in blocks:
        lines = [ln.strip() for ln in block.strip().splitlines() if ln.strip()]
        if len(lines) < 2:
            continue
        # 첫 줄은 인덱스 (숫자), 두 번째 줄은 타이밍
        timing_idx = 1 if lines[0].isdigit() else 0
        if timing_idx >= len(lines):
            continue
        timing = lines[timing_idx]
        if "-->" not in timing:
            continue
        start_s, end_s = timing.split("-->", 1)
        start = _parse_srt_time(start_s)
        end = _parse_srt_time(end_s)
        text = "\n".join(lines[timing_idx + 1:]).strip()
        if text:
            entries.append((start, end, text))

    if not entries:
        return False

    header = _build_ass_header(style_dict)
    body = "\n".join(
        _build_dialogue_line(s, e, t, style_dict) for s, e, t in entries
    )

    try:
        Path(out_ass_path).write_text(header + body + "\n", encoding="utf-8")
        return True
    except Exception:
        return False


def lrc_to_ass(
    lrc_path: str,
    out_ass_path: str,
    style: str = "ballad",
    default_line_duration: float = 4.0,
) -> bool:
    """LRC 파일 → ASS 직접 변환 (SRT 경유 안 함)."""
    style_dict = STYLE_PRESETS.get(style) or STYLE_PRESETS["ballad"]

    try:
        content = Path(lrc_path).read_text(encoding="utf-8")
    except Exception:
        return False

    time_pat = re.compile(r"(\[\d+:\d+(?:[.:]\d+)?\])(.*)")
    entries: list[tuple[float, str]] = []

    for line in content.splitlines():
        line = line.strip()
        if not line:
            continue
        # [Verse], [Chorus] 섹션 태그 스킵
        if line.startswith("[") and not time_pat.match(line):
            continue
        m = time_pat.match(line)
        if not m:
            continue
        tag, text = m.groups()
        text = text.strip()
        if not text:
            continue
        start = _parse_lrc_time(tag)
        entries.append((start, text))

    if len(entries) < 1:
        return False
    entries.sort(key=lambda x: x[0])

    header = _build_ass_header(style_dict)
    lines = []
    for i, (start, text) in enumerate(entries):
        if i + 1 < len(entries):
            end = entries[i + 1][0] - 0.05
        else:
            end = start + default_line_duration
        if end <= start:
            end = start + default_line_duration
        lines.append(_build_dialogue_line(start, end, text, style_dict))

    try:
        Path(out_ass_path).write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
        return True
    except Exception:
        return False


def pick_style_for(style_name: str) -> str:
    """youtube_uploader 의 style_name → ass_subtitles 프리셋 매핑."""
    if style_name in ("pop", "kpop"):
        return "pop"
    if style_name in ("lofi", "jazz", "study", "classical"):
        return "lofi"
    if style_name in ("sleep", "meditation", "rain"):
        return "emotional"
    return "ballad"


if __name__ == "__main__":
    import tempfile

    # LRC 테스트
    sample_lrc = """[Verse]
[00:02.00]첫 가사 한 줄
[00:06.50]두 번째 라인
[00:11.00]세 번째 라인

[Chorus]
[00:16.00]사랑해
[00:20.00]너를
"""
    with tempfile.NamedTemporaryFile(suffix=".lrc", delete=False, mode="w", encoding="utf-8") as f:
        f.write(sample_lrc)
        lrc_path = f.name
    ass_path = lrc_path.replace(".lrc", ".ass")
    assert lrc_to_ass(lrc_path, ass_path, style="ballad")
    out = Path(ass_path).read_text(encoding="utf-8")
    assert "[Script Info]" in out
    assert "[V4+ Styles]" in out
    assert "Malgun Gothic" in out
    assert "\\fad(" in out
    assert "첫 가사 한 줄" in out
    assert "Verse" not in out  # 섹션 마커는 자막에서 제외

    # SRT 테스트
    sample_srt = """1
00:00:02,000 --> 00:00:06,000
첫 가사 한 줄

2
00:00:06,500 --> 00:00:11,000
두 번째 라인
"""
    with tempfile.NamedTemporaryFile(suffix=".srt", delete=False, mode="w", encoding="utf-8") as f:
        f.write(sample_srt)
        srt_path = f.name
    ass_path2 = srt_path.replace(".srt", ".ass")
    assert srt_to_ass(srt_path, ass_path2, style="pop")
    out2 = Path(ass_path2).read_text(encoding="utf-8")
    assert "첫 가사 한 줄" in out2
    assert "두 번째 라인" in out2

    # 스타일 매핑
    assert pick_style_for("pop") == "pop"
    assert pick_style_for("lofi") == "lofi"
    assert pick_style_for("sleep") == "emotional"
    assert pick_style_for("unknown") == "ballad"

    print("✓ ass_subtitles.py 자체 테스트 통과")
    print(f"샘플 ASS 파일: {ass_path}")
